#!/bin/bash

rm -r src/projector/shaders.h;

echo "// File auto generated by compile-shaders.sh" >> src/projector/shaders.h;
echo "// Edit instead shaders in src/shaders" >> src/projector/shaders.h;


for file in src/shaders/*; do
    shader_str=$(cat "$file" | sed 's/$/\\n/' | tr -d '\n');
    shader_define=$(basename "$file" | tr '-' '_' | tr '.' '_' | tr 'a-z' 'A-Z');
    echo "#define $shader_define \"$shader_str\"" >> src/projector/shaders.h;
done;
